### ISSUE TITLE
Extension key for composer.json

### ISSUE THREAD

**Issue by ayacoo** [manuelselbach/static_info_tables_ru#12]
The TYPO3 extension package "mselbach/static-info-tables-ru", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by manuelselbach** [comment]
Thanks @ayacoo for reporting this issue. I'll take care in the next days.

**Comment by ayacoo** [comment]
Hint: It's aready in the master. Just not tagged/releases yet.

**Comment by manuelselbach** [comment]
@ayacoo "next days" took a bit longer 🙈 I checked this and the extension key should be available in the tagged version 11.5.0. What version are you looking at?

**Comment by ayacoo** [comment]
@manuelselbach This has affected the older versions: https://github.com/manuelselbach/static_info_tables_ru/blob/6.9.0/composer.json

**Comment by manuelselbach** [comment]
@ayacoo Is this still relevant e.g. for projects that use ELTS version? I'm not sure, how I'm able to get an installable set of packages via composer using the "roave/security-advisories". Is there any documentation how I'm able to do so?

Anyways, are you able to test the changes in branch 6.9.x? If everything is fine, I'll tag a new version. Thanks in advance for your support ☺️

**Comment by ayacoo** [comment]
I'll leave that up to you if you want to adjust anything else. I would be in favour of a look ahead in the development. Moreover, there was no further feedback on this issue.

For us it is no longer relevant because we have upgraded to v11.

**Comment by manuelselbach** [comment]
I've released version 6.9.1 with the `extension-key` available in the composer.json. Thanks again for the hint ☺️

**Comment by manuelselbach** [comment]
`extension-key` is available in version 6.9.1 ☺️
