### ISSUE TITLE
Add TYPO3 CMS 8.x support

### ISSUE THREAD

**Issue by josefglatz** [manuelselbach/static_info_tables_ru#2]

**Comment by manuelselbach** [comment]
Hi @jousch,

thanks for your interest.
I've updated the extension in the following branch:
https://github.com/manuelselbach/static_info_tables_ru/tree/feature/2_Add_TYPO3_CMS_8.x_support

It would be very nice if you could verify that everything works correctly.
Thanks in advance.

**Comment by josefglatz** [comment]
Nice Nice!thank you!  K, will test it soon today

Cheers

Von meinem iPhone gesendet
