### ISSUE TITLE
Can not redeclare SJBR \ StaticInfoTables \ Domain \ Model \ Country :: $ shortNameRu

### ISSUE THREAD

**Issue by fritzdacat** [manuelselbach/static_info_tables_ru#3]
Unfortunately I always get this error after updating TYPO3 6 to TYPO3 7:
Fatal error: Can not redeclare SJBR \ StaticInfoTables \ Domain \ Model \ Country :: $ shortNameRu in /Volumes/Webs/htdocs/intercultureUpdate/interculture_t3/typo3temp/Cache/Code/static_info_tables/DomainModelCountry.php on line 630

Installed static-info-tables extension:
"typo3-ter / static-info-tables": "6.4.3",
"typo3-ter / static-info-tables-DE": "6.4.0",
"typo3-ter / static-info-tables-es": "6.4.2",
"typo3-ter / static-info-tables-ru": "6.4.0",

**Comment by manuelselbach** [comment]
@fritzdacat 
How do you install the extensions via composer or the extension manager?
Where does this error occur? In the backend, the frontend?

**Comment by manuelselbach** [comment]
I close this issue as there was no further information provided.
